### PR TITLE
Reorganised typings to expose the filterXSS function

### LINKED ISSUE #154: Function filterXSS isn't exported in TS typings
Hi,
it appears to me that the function `filterXSS` is not exported from the typings - making the "shim mode" example from https://jsxss.com/en/starter/quickstart.html not work. I would submit a PR, but I am unfortunately lost in JS modules as I don't use them personally.

Thank you

### PR DESCRIPTION
**Pull request by GenaBitu**
Fixes #154 
Maybe breaks something else. I haven't yet figured out, how to run the typings tests.

### CODE REVIEW

**Comment by leizongmin** [comment]
Thanks. I have published a new version `xss@1.0.4`.

**Comment by leizongmin** [comment]
I found that is some problems. So I please try the newest version `xss@1.0.4`, it exports an `filterXSS` function.
See https://github.com/leizongmin/js-xss/commit/ad46d0aa0e1ce4d07ac9139ae14ed37c278a09a3

**Comment by GenaBitu** [comment]
Hi,
thanks, the typings for the `filterXSS` function are available now. However, I cannot access `IFilterXSSOptions` now - I think if they were to be moved to the declare global block, they would be available, but maybe they really should be namespaced to not pollute the global namespace. I don't know...

Anyway, thank you...

**Comment by leizongmin** [comment]
You can try this:

```typescript
import * as xss from "xss";

const options: xss.IFilterXSSOptions = {}
```

**Comment by leizongmin** [comment]
I just add the global `XSS` namespace back, please try `xss@1.0.5`:

```typescript
// interface or type don't required to import "xss" module, just use "XSS" namespace
// but filterXSS function still need to import "xss" module
const options: XSS.IFilterXSSOptions = {}
```

**Comment by GenaBitu** [comment]
Hey, I've tried it and it all works now, thanks a lot. I used the `XSS` namespace, because I'm not using imports...

Done and thank you.

**Pull request merged**
