### PR TITLE
Fix 'DedicatedWorkerGlobalScope is not defined' error on Web env

### PR DESCRIPTION
**Pull request by Asvarox**
This fixes code added in https://github.com/leizongmin/js-xss/commit/723b307a32541044e4f4dcbb260c34b3168e87f2 which causes #140 

I didn't commit built version because that'd could be a chance for me to put nasty code in the minified file without anybody noticing :) .

### CODE REVIEW

**Comment by leizongmin** [comment]
I am very sorry for such mistakes. I have merged this pull request and published the new version `xss@1.0.3`. Thanks.

**Comment by l9c** [comment]
Commit 7ecfb03 is missing in the xss@1.0.3 released files. Please fix it. Thanks

**Comment by leizongmin** [comment]
@l9c I just checked the `npm i xss@1.0.3` and I am sure this commit is already included. Maybe that is another problem?

**Comment by l9c** [comment]
@leizongmin That's weird!  I've checked the file https://github.com/leizongmin/js-xss/archive/v1.0.3.zip again, please see dist/xss.js line 453
image

see [the archive file submitted to VirusTotal](https://www.virustotal.com/#/file/ab8e15d4a109f76dcf83af874d351ef5529daf3a7788db27a3d62919c4bb0af2/detection)

**It seems that the [npm package](https://registry.npmjs.org/xss/-/xss-1.0.3.tgz) is not consistent with github/bower** 

Thanks for the reply.

**Comment by leizongmin** [comment]
@l9c 
I found the problem is the `v1.0.3` tag was on a wrong commit, and now I've fixed this.
Please try again? (I am very sorry)

**Comment by l9c** [comment]
It's OK now. Thanks!
BTW: cache clean is required before reinstalling with bower.

**Pull request merged**
