### PR TITLE
feat: add support for allowList as an alias for whiteList

### PR DESCRIPTION
**Pull request by schu34**
addresses #219

### CODE REVIEW

**Comment by schu34** [comment]
@leizongmin Thanks for merging! Any idea when the next release will go out?

**Comment by yyandapalli** [comment]
@leizongmin 
Hope you are doing well
Any idea when the next release will go out?

**Comment by leizongmin** [comment]
@schu34 @yyandapalli I have just publish a new version `xss@1.0.11` that includes this change.

**Comment by yyandapalli** [comment]
Thank you very much, highly appreciate

**Comment by yyandapalli** [comment]
Hi @leizongmin,
My team is trying to use this new version of xss (1.0.11) and getting below error with this new version:

file.ts:27:25 - error TS2339: Property 'escapeAttrValue' does not exist on type '(html: string, options?: IFilterXSSOptions) => string'.

27       ? `${name}="${xss.escapeAttrValue(value)}"`
                           ~~~~~~~~~~~~~~~

file.ts:32:7 - error TS2339: Property 'filterXSS' does not exist on type '(html: string, options?: IFilterXSSOptions) => string'.

32   xss.filterXSS(dangerousHTML, makeXssOptions());
====
Any idea on why these errors are coming? Is it because of the changes done in xss.d.ts?
Any guidance is much appreciated

**Comment by yyandapalli** [comment]
Never mind, ignore this
We had to change the import as below to fix this:
import * as xss from "xss"

**Pull request merged**
